### ISSUE TITLE
Design primers for unknown bacteria species

### ISSUE THREAD

**Issue by penguin335** [biologger/speciesprimer#25]
Hi,

Can I design specific primers for an unknown species (Namely no entry in NCBI database)?
I have a genome assembly file (.fna) and a .gff file for this unknown species.

Thank you in advance.

**Comment by abliu** [comment]
I would also be interested in this. I would like to design primers for species for which I have my own set of genome assemblies (I don't want to download the assemblies from NCBI). I saw the `offline` and `skip_download` command line options--are those what I would want to use?

Thank you for creating this tool!

**Comment by biologger** [comment]
Hi,
Yes, this is possible using the "offline" option if you have more than one genome assembly. 
In order to create the directory structure you can create them manually 
```
$ mkdir Unknown_species
$ mkdir Unknown_species/genomic_fna
```
Subsequently, copy the assembly fna files to the "genomic_fna" directory. Afterwards run speciesprimer.py with the offline option

Alternatively, run batchassist.py and follow the prompts and make sure you select the offline option (this will create the config files and directories) 

`$ batchassist.py
`
Subsequently, copy the assembly fna files to the "genomic_fna" directory.
Afterwards run speciesprimer.py and "continue" the run.
