### ISSUE TITLE
primer_1_results.xml absent?

### ISSUE THREAD

**Issue by aiqubo** [biologger/speciesprimer#4]
"""27 Apr 2020 19:32:14: > Error report:
27 Apr 2020 19:32:14: > for target Bifidobacterium_animalis
27 Apr 2020 19:32:14: > Error 1:
27 Apr 2020 19:32:14: > A problem with the BLAST results file /primerdesign/Bifidobacterium_animalis/Pangenome/results/primer/primerblast/primer_1_results.xml was detected. Please check if$
27 Apr 2020 19:32:14: > for target Bifidobacterium_animalis
27 Apr 2020 19:32:14: > Error 2:
27 Apr 2020 19:32:14: > fatal error while working on Bifidobacterium_animalis check logfile /primerdesign/speciesprimer_2020_04_27.log
"""

"""
root@c5299f64bf4d:/primerdesign/Bifidobacterium_animalis/Pangenome/results/primer/primerblast# ls
primer.part-0  primer.part-1  primer.part-2  primer.part-3  primer_0_results.xml  primer_2_results.xml  primer_3_results.xml
"""
There isn't primer_1_results.xml file in this folder ,how can i fix this error? help me pls

**Comment by biologger** [comment]
Hi,
I have to check why not the full error message is displayed. The full error message is:
> A problem with the BLAST results file /primerdesign/Bifidobacterium_animalis/Pangenome/results/primer/primerblast/primer_1_results.xml was detected. Please check if the file was removed and start the run again"

I cannot say what was the problem with the file, but it was removed. If you restart the run it should run the BLAST search only for primer.part-1 and continue.

**Comment by aiqubo** [comment]
yes, it was removed, I restart the run, report tihs error again. I copy a primer_1_results.xml in /primerdesign/Bifidobacterium_animalis/Pangenome/results/primer/primerblast/, and restart the run, it was removed again.
how to fix it? Any Suggestions?

**Comment by biologger** [comment]
Copying an primer_1_results.xml file is probably not working because the file is removed if any xml parsing Error occurs.

Maybe you could try to do the blast step manually to see why the BLAST step fails.

```
$ cd /primerdesign/Bifidobacterium_animalis/Pangenome/results/primer/primerblast
$ blastn -task blastn-short -num_threads 8 -query primer.part-1 -evalue 500 -out primer_1_results.xml -outfmt 5 -db ref_prok_rep_genomes
```
In case the BLAST step is successful copy it to another directory before you try to restart the run.
`cp primer_1_results.xml /primerdesign/primer_1_results.xml`

In case the run fails again with the same error inspect the xml file and see what could be wrong.
If you are able to send the large xml file to me I am happy to help.

If this is not solving the problem please also provide the configuration of the run.
`$ cat /primerdesign/Bifidobacterium_animalis/config/config.json`

**Comment by aiqubo** [comment]
Thank you very much, I will try as you suggest, and I will let you know any progress.

aiqubo
发自我的 iPhone

在 2020年4月28日，下午7:42，biologger <notifications@github.com> 写道：

﻿

Copying an primer_1_results.xml file is probably not working because the file is removed if any xml parsing Error occurs.

Maybe you could try to do the blast step manually to see why the BLAST step fails.

$ cd /primerdesign/Bifidobacterium_animalis/Pangenome/results/primer/primerblast
$ blastn -task blastn-short -num_threads 8 -query primer.part-1 -evalue 500 -out primer_1_results.xml -outfmt 5 -db ref_prok_rep_genomes


In case the BLAST step is successful copy it to another directory before you try to restart the run.
cp primer_1_results.xml /primerdesign/primer_1_results.xml

In case the run fails again with the same error inspect the xml file and see what could be wrong.
If you are able to send the large xml file to me I am happy to help.

If this is not solving the problem please also provide the configuration of the run.
$ cat /primerdesign/Bifidobacterium_animalis/config/config.json

**Comment by aiqubo** [comment]
yes,it is not solving the problem

/primerdesign/Bifidobacterium_animalis/config/config.json
`{"blastdbv5": false, "ignore_qc": false, "probe": true, "blastseqs": 1000, "maxsize": 120, "mfold": -3.0, "mfethreshold": 90, "exception": [], "intermediate": false, "assemblylevel": ["all"], "qc_gene": ["rRNA"], "mpprimer": -3.5, "customdb": "ref_prok_rep_genomes", "nolist": false, "offline": true, "target": "Bifidobacterium_animalis", "skip_download": false, "minsize": 60, "skip_tree": false, "path": "/primerdesign"}`

you can download "primer_1_results.xml" file, as follow link, it about 339Mb, need to download it within 7 days.
[https://send.firefox.com/download/8c06f3913efa1232/#gQ7NnRsGrPmfV_xynCNFLA](url)

Thanks for your kind offer of help.

**Comment by biologger** [comment]
Thanks for providing the file. 
There is in fact a problem with the xml file. After Query 636 it ends without ending the xml tree elements.
You can see this if you are comparing this file with your other result files.
```
$ grep -e "<Iteration_query-ID>" primer_0_results.xml
$ grep -e "<Iteration_query-ID>" primer_1_results.xml

$ tail primer_0_results.xml
$ tail primer_1_results.xml
```

Adding the ending of the tree elements to the primer_1_results.xml fixes the error.
However, this is not a solution for your run because you would miss hundreds of BLAST results!

It seems as blastn is writing the results and then suddenly stops. 
I was not able to reproduce this behaviour so I can only speculate why this may happen. Since blastn is not reporting any error, it is maybe just killed at some point. Could be a problem with memory or writing to the harddisk. How much memory (RAM) is available on your computer?

Since the results are written until Query 636 I would suggest you change the blastseqs option to 500 (instead of 1000). Delete the primerblast directory and restart the run. 
Now the BLAST search will be split into eight parts. This should use less memory, the writing should be a bit faster and therefore less prone to interruptions.

I hope this helps!

**Comment by aiqubo** [comment]
Thank you very much!
I will change the blastseqs option to 500 and restart the run, 16G memory (RAM) is available on my computer
`root@c5299f64bf4d:/primerdesign# free -m
              total        used        free      shared  buff/cache   available
Mem:          15885        8988         169           0        6726        6593
Swap:             0           0           0`

**Comment by aiqubo** [comment]
work now, thank you for your kind help
